### PR TITLE
Allow semver-compatible frontend versions

### PR DESCRIPTION
**Pull request by kylebarron**
In relation to the discussion about JupyterHub in https://github.com/manzt/anywidget/issues/385, I've suggested to a few of my users to install anywidget on the server, then install lonboard in the client environment. Lonboard does not pin a version of anywidget, so when a new anywidget version is released, the next install of lonboard will break because the client anywidget version does not exactly match the server anywidget version.

I have reason to believe that using `"~major.minor.*"` works, because pydeck has been doing that for its frontend code for a while, to allow the Python code and JS bindings to be versioned separately (see [1](https://github.com/visgl/deck.gl/blob/9117414ef894b8755e0eff33e7cf503a2137249f/bindings/pydeck/pydeck/frontend_semver.py#L1), [2](https://github.com/visgl/deck.gl/blob/ff7566644bc716cf917c0f21e8155b5ff1074b7a/bindings/pydeck/pydeck/widget/_frontend.py#L14), [3](https://github.com/visgl/deck.gl/blob/9117414ef894b8755e0eff33e7cf503a2137249f/bindings/pydeck/pydeck/widget/widget.py#L55)). 

That said, I haven't yet tested this in a JupyterHub environment. (I haven't tried to set up the development environment yet)

### CODE REVIEW

**Comment by manzt** [comment]
Hey, just wanted to check in on this. I notice the PR is still in a Draft state. I should have some time to push it forward if that is ok with you. Thanks!

**Comment by kylebarron** [comment]
I only set it as "draft" because I hadn't figured out how to test it yet. But it "looks" valid based on what pydeck was using

**Comment by manzt** [comment]
Ah, sorry for the misunderstanding. I thought it wasn't ready for review. I'll have a look and get back to you :) thanks for the contribution!

**Comment by manzt** [comment]
Ok, I tried this out in a few different environments (Lab, standalone HTML, Colab) and things seem to be working. The various CDN importers seem to resolve the version specifier correctly, which would be the main thing I would worry about. 

I think this should be seen as a temporary fix. I still think we should ideally separately version the anywidget frontend in the future.

**Comment by kylebarron** [comment]
awesome 🙌

**Pull request merged**
