### PR TITLE
Change order of "Next steps" in create-anywidget

### PR DESCRIPTION
**Pull request by dvdkouril**
Reasoning in #475

### CODE REVIEW

**Comment by manzt** [comment]
Thanks for the contribution! The error is coming from some tests i have to make sure the exact output of the cli stays the same. You can update the snapshots with pnpm vitest and u to update the snapshot. Otherwise i can take care of it later :)

**Comment by dvdkouril** [comment]
Hm, I thought the error's coming from some linting line length rule applied on the changeset.
Anyway, I also realized, that it probably makes sense to have it:
1. `cd`
2. `npm install`
3. `git stuff`
4. `npm run dev`
5. `"To close..."`

While what I committed gives:
1. `cd` 
2. `npm install`
3. `npm run dev`
4. `"To close..."`
5. `git stuff`

and `npm run dev` hijacks your shells so you don't even get to do your commit.

**Comment by manzt** [comment]
> Hm, I thought the error's coming from some linting line length rule applied on the changeset.

Ah ya, you are right. Just need to run `pnpm format`.

> Anyway, I also realized, that it probably makes sense to have it

Yah, I like this option, running `npm run dev` last (after optional git stuff).

**Comment by manzt** [comment]
@dvdkouril I took a stab at your suggested changes. Look ok?

**Comment by dvdkouril** [comment]
Yes! So sorry I let this one rot. I was thinking whether there's a way to write it without repeating the if loop.
But this looks good to me.

**Pull request merged**
