### PR TITLE
feat: Add a example notebook to the cookiecutter

### PR DESCRIPTION
**Pull request by kolibril13**
I've tested all 5 options with 

cd packages/create-anywidget
npm install
node index.js

there was one tricky part:
"from ${name} import Counter\n",
had to be replaced with 
"from ${name} import Counter\\n",

but now everything works fine.

### CODE REVIEW

**Comment by kolibril13** [comment]
in action:

https://github.com/manzt/anywidget/assets/44469195/dbb7fe94-f7e2-475a-9951-18156a3bc1f4

**Comment by manzt** [comment]
> there was one tricky part:
"from ${name} import Counter\n",
had to be replaced with
"from ${name} import Counter\n",

I don't see the difference between these two lines

**Comment by kolibril13** [comment]
image

**Comment by manzt** [comment]
can you just include an empty line?

```
	"cell_type": "code",
		"execution_count": null,
		"metadata": {},
		"outputs": [],
		"source": [
		"from ${name} import Counter",
                "",
		"Counter()"
		]
```

**Comment by kolibril13** [comment]
I just tried the empty line approach
image
and that renders like this in VSCode notebook:
image

And like this in JupyterLab
image

**Review by manzt — APPROVED** [review]
Just updated the snapshots for testing. LGTM! Thanks

**Pull request merged**
