### PR TITLE
feat(create-anywidget): Add "readme" to pyproject.toml template

### PR DESCRIPTION
**Pull request by kolibril13**
This pr is adding readme = "README.md" 
This way e.g.

image

will become

image

### CODE REVIEW

**Comment by manzt** [comment]
Thanks! Just changed the name of the PR because I want to avoid using the name "cookiecutter" for our CLI. It doesn't use [cookiecutter](https://cookiecutter.readthedocs.io/en/stable/) and helps destinguish our CLI fro the existing cookiecutters from Jupyter.

**Review by manzt — CHANGES_REQUESTED** [review]
Looks great! Thanks. CI is failing because we have a test to generate some repos using the CLI and take a "snapshot" of the output files. 

The line added in this PR now is in each snapshot (good), causing it to fail, so we need to update the snapshot. Please:

```sh
cd packages/create-anywidget
```

```sh
pnpm vitest --update # updates snapshot
```

And make sure the diff looks correct. Check in the new snapshots.

Then go to the repo root:

```sh
cd ../../
```

and create a changeset for create-anywidget. 

```sh
pnpm changeset # follow prompt
```

**Comment by manzt** [comment]
Don't want this to go stale. In the future, please follow the steps outlined above for making a contribution for `create-anywidget`.

**Comment by kolibril13** [comment]
hi @manzt,
thanks for updating the snapshot and for merging the pr!

**Pull request merged**
